name: 🐛 Report a bug
description: If you have found a bug on Strelix Core report it here!
title: "bug: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |

        Hey there, thanks for creating a bug report, it's much appreciated!
        > Note: This is strictly for **bug** reports for the **CORE** repository, issues regarding myfinances should be posted 
        on the [MyFinances Repo](https://github.com/Trey/MyFinances)

        Before creating the bug report, please make sure that you have done the following steps:
        - [ ] Only post **one** problem *per* bug report
        - [ ] Updated to the latest [official release](https://github.com/Strelix/Core/releases)
        - [ ] Update your database with the latest migrations `py manage.py migrate`

  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What version of Strelix-Core are you currently using?
      description: You can view by using the command `git describe --tags`
      placeholder: "v0.1.0"
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: |
        Please describe the bug in detail, make sure to list HOW you get the bug to come up (steps exactly what you follow, including the page path)
        > To use code blocks, use ``` at the start and end of your code snippets. DO NOT USE SCREENSHOTS OF CODE.

        You may attach images, please upload directly using github